
List<Map<String, dynamic>> allChats = [
  {
    'id': 1,
    'name': 'Amancio Ortega',
    'desc': '...',
    'time': '12:45 PM',
    'number': '+91 1643193235',
    'image': 'assets/images/Amancio ortega.webp',

  },
  {
    'id': 2,
    'name': 'Michael Bloomberg',
    'desc': 'bolo',
    'time': 'Yesterday',
    'number': '+91 2643193235',
    'image': 'assets/images/Michael Bloomberg.webp',
  },
  {
    'id': 3,
    'name': 'Bernard Arnault',
    'desc': 'sun ',
    'time': '4:10 AM',
    'number': '+91 3643193235',
    'image': 'assets/images/Bernard Arnault.webp',
  },
  {
    'id': 4,
    'name': 'Bill Gates',
    'desc': 'pdda',
    'time': '3:25 PM',
    'number': '+91 4643193235',
    'image': 'assets/images/Bill Gates.webp',
  },
  {
    'id': 5,
    'name': 'Carlos Slim Helu',
    'desc': 'hii',
    'time': '12:00 PM',
    'number': '+91 5643193235',
    'image': 'assets/images/Carlos Slim Helu.webp',
  },
  {
    'id': 6,
    'name': 'Jeff Bezos',
    'desc': 'location',
    'time': 'Now',
    'number': '+91 6643193235',
    'image': 'assets/images/Jeff Bezos.webp',
  },
  {
    'id': 7,
    'name': 'Larry Ellison',
    'desc': 'ok',
    'time': '2:45 PM',
    'number': '+91 7643193235',
    'image': 'assets/images/Larry Ellison.webp',
  },
  {
    'id': 8,
    'name': 'Mark Zukerberg',
    'desc': 'hy',
    'time': '1:05 PM',
    'number': '+91 8643193235',
    'image': 'assets/images/Mark Zukerberg.webp',
  },
];
List<Map<String, dynamic>> allCalls = [
  {
    'name': 'Amancio Ortega',
    'desc': '...',
    'time': '12:45 PM',
    'number': '+91 1643193235',
    'image': 'assets/images/Amancio ortega.webp',

  },
  {
    'name': 'Michael Bloomberg',
    'desc': 'bolo',
    'time': 'Yesterday',
    'number': '+91 2643193235',
    'image': 'assets/images/Michael Bloomberg.webp',
  },
  {
    'id': 3,
    'name': 'Bernard Arnault',
    'desc': 'sun ',
    'time': '4:10 AM',
    'number': '+91 3643193235',
    'image': 'assets/images/Bernard Arnault.webp',
  },
  {
    'id': 4,
    'name': 'Bill Gates',
    'desc': 'hii',
    'time': '3:25 PM',
    'number': '+91 4643193235',
    'image': 'assets/images/Bill Gates.webp',
  },
  {
    'id': 5,
    'name': 'Carlos Slim Helu',
    'desc': 'hii',
    'time': '12:00 PM',
    'number': '+91 5643193235',
    'image': 'assets/images/Carlos Slim Helu.webp',
  },
  {
    'id': 6,
    'name': 'Jeff Bezos',
    'desc': 'location',
    'time': 'Now',
    'number': '+91 6643193235',
    'image': 'assets/images/Jeff Bezos.webp',
  },
  {
    'id': 7,
    'name': 'Larry Ellison',
    'desc': 'ok',
    'time': '2:45 PM',
    'number': '+91 7643193235',
    'image': 'assets/images/Larry Ellison.webp',
  },
  {
    'id': 8,
    'name': 'Mark Zukerberg',
    'desc': 'hy',
    'time': '1:05 PM',
    'number': '+91 8643193235',
    'image': 'assets/images/Mark Zukerberg.webp',
  },
];
List<Map<String, dynamic>> allStatus = [
  {
    'name': 'Amancio Ortega',
    'time': 'Today, 12:45 PM',
    'image': 'assets/images/Amancio ortega.webp',
  }, {
    'name': 'Bernard Arnault',
    'time': 'yesterday, 2:05 PM',
    'image': 'assets/images/Bernard Arnault.webp',
  }, {
    'name': 'Bill Gates',
    'time': 'Tuesday, 1:40 PM',
    'image': 'assets/images/Bill Gates.webp',
  }, {
    'name': 'Carlos Slim Helu',
    'time': ' now, 12:45 PM',
    'image': 'assets/images/Carlos Slim Helu.webp',
  },
];
